function TBL = run_refinement_depth_sweep()
%RUN_REFINEMENT_DEPTH_SWEEP Stress-test mode 1 center count and mode 3 depth.
% Ignores mode 2. Designed for the mild/current schedule.

old_no_plots = getenv('PENDULUM_NO_PLOTS');
old_overrides = getenv('PENDULUM_OVERRIDES');
old_keep_workspace = getenv('PENDULUM_KEEP_WORKSPACE');
cleanup = onCleanup(@() restore_env(old_no_plots, old_overrides, old_keep_workspace));

setenv('PENDULUM_NO_PLOTS', '1');
setenv('PENDULUM_KEEP_WORKSPACE', '1');

base = struct( ...
    'plant_schedule', 'current', ...
    'hybrid_budget_mode', 'fixed', ...
    'fixed_budget_law', 'constant');

tests = {};
tests{end+1} = make_test('m1_default_2_3_5', base, ...
    state_layout(40, struct('kernel_mode', 1)));
tests{end+1} = make_test('m1_grid_4_6_8', base, ...
    state_layout(80, struct('kernel_mode', 1, ...
                            'kernel_mode1_grid_sequence', [4 6 8], ...
                            'kernel_mode1_max_grid_n', 8)));
tests{end+1} = make_test('m1_grid_6_8_10', base, ...
    state_layout(120, struct('kernel_mode', 1, ...
                             'kernel_mode1_grid_sequence', [6 8 10], ...
                             'kernel_mode1_max_grid_n', 10)));
tests{end+1} = make_test('m1_grid_8_10_12', base, ...
    state_layout(160, struct('kernel_mode', 1, ...
                             'kernel_mode1_grid_sequence', [8 10 12], ...
                             'kernel_mode1_max_grid_n', 12)));
tests{end+1} = make_test('m1_dense_12', base, ...
    state_layout(160, struct('kernel_mode', 1, ...
                             'kernel_mode1_grid_sequence', 12, ...
                             'kernel_mode1_max_grid_n', 12)));

tests{end+1} = make_test('m3_default_depth7', base, ...
    state_layout(40, struct('kernel_mode', 3, ...
                            'kernel_rep_point', 'endpoint', ...
                            'max_depth', 7)));
tests{end+1} = make_test('m3_depth9_endpoint', base, ...
    state_layout(40, struct('kernel_mode', 3, ...
                            'kernel_rep_point', 'endpoint', ...
                            'max_depth', 9)));
tests{end+1} = make_test('m3_depth11_endpoint', base, ...
    state_layout(40, struct('kernel_mode', 3, ...
                            'kernel_rep_point', 'endpoint', ...
                            'max_depth', 11)));
tests{end+1} = make_test('m3_depth9_maxerr', base, ...
    state_layout(40, struct('kernel_mode', 3, ...
                            'kernel_rep_point', 'max_tracking_error', ...
                            'max_depth', 9)));
tests{end+1} = make_test('m3_depth11_maxerr', base, ...
    state_layout(40, struct('kernel_mode', 3, ...
                            'kernel_rep_point', 'max_tracking_error', ...
                            'max_depth', 11)));
tests{end+1} = make_test('m3_depth9_tight_window', base, ...
    state_layout(40, struct('kernel_mode', 3, ...
                            'kernel_rep_point', 'max_tracking_error', ...
                            'max_depth', 9, ...
                            'kernel_l2_high', 0.01, ...
                            'kernel_l2_low', 0.005)));
tests{end+1} = make_test('m3_depth11_loose_window', base, ...
    state_layout(40, struct('kernel_mode', 3, ...
                            'kernel_rep_point', 'max_tracking_error', ...
                            'max_depth', 11, ...
                            'kernel_l2_high', 0.04, ...
                            'kernel_l2_low', 0.015)));

results = repmat(empty_result(), numel(tests), 1);
for k = 1:numel(tests)
    fprintf('\n===== REFINEMENT SWEEP %d/%d: %s =====\n', ...
        k, numel(tests), tests{k}.name);
    results(k).name = tests{k}.name;
    try
        metrics = run_one_candidate(tests{k}.overrides);
        fields = fieldnames(metrics);
        for f = 1:numel(fields)
            results(k).(fields{f}) = metrics.(fields{f});
        end
        fprintf(['L2 full=%.6f, L2 2-5=%.6f, L2 5-10=%.6f, ' ...
                 'theta RMSE 5-10=%.4f deg, max theta 5-10=%.4f deg, ' ...
                 'centers final/mean/max=%g/%.1f/%g, updates=%g\n'], ...
            results(k).l2_full, results(k).l2_2_5, results(k).l2_5_10, ...
            results(k).theta_rmse_5_10, results(k).max_abs_theta_err_5_10, ...
            results(k).final_centers, results(k).mean_centers, ...
            results(k).max_centers, results(k).kernel_updates);
    catch ME
        results(k).error = ME.message;
        fprintf('FAILED: %s\n', ME.message);
    end
end

TBL = sortrows(struct2table(results), 'l2_5_10', 'ascend');
disp(TBL);
end

function result = empty_result()
result = struct( ...
    'name', '', ...
    'l2_full', NaN, ...
    'l2_2_5', NaN, ...
    'l2_5_10', NaN, ...
    'theta_rmse_5_10', NaN, ...
    'theta_dot_rmse_5_10', NaN, ...
    'max_abs_theta_err_5_10', NaN, ...
    'final_centers', NaN, ...
    'mean_centers', NaN, ...
    'max_centers', NaN, ...
    'kernel_updates', NaN, ...
    'control_rms', NaN, ...
    'error', '');
end

function metrics = run_one_candidate(overrides)
setenv('PENDULUM_NO_PLOTS', '1');
setenv('PENDULUM_KEEP_WORKSPACE', '1');
setenv('PENDULUM_OVERRIDES', jsonencode(overrides));

evalc('run(''Main_sim.m'')');

T = LOG.T;
X = LOG.X;
e = X(:,1:2) - X(:,3:4);
idx_late = T >= 5 & T <= 10;
idx_mid = T >= 2 & T < 5;

metrics.l2_full = SIM_METRICS.tracking_l2;
metrics.l2_2_5 = sqrt(trapz(T(idx_mid), sum(e(idx_mid,:).^2, 2)));
metrics.l2_5_10 = sqrt(trapz(T(idx_late), sum(e(idx_late,:).^2, 2)));
metrics.theta_rmse_5_10 = sqrt(mean(rad2deg(e(idx_late,1)).^2));
metrics.theta_dot_rmse_5_10 = sqrt(mean(rad2deg(e(idx_late,2)).^2));
metrics.max_abs_theta_err_5_10 = max(abs(rad2deg(e(idx_late,1))));
if exist('Xi_hist', 'var') && ~isempty(Xi_hist)
    center_counts = cellfun(@(Xi) size(Xi, 1), Xi_hist(:));
    metrics.final_centers = center_counts(end);
    metrics.mean_centers = mean(center_counts);
    metrics.max_centers = max(center_counts);
else
    metrics.final_centers = 0;
    metrics.mean_centers = 0;
    metrics.max_centers = 0;
end
metrics.kernel_updates = SIM_METRICS.kernel_updates;
metrics.control_rms = SIM_METRICS.control_rms;
end

function test = make_test(name, base, overrides)
test.name = name;
test.overrides = merge_struct(base, overrides);
end

function s = merge_struct(a, b)
s = a;
fields = fieldnames(b);
for i = 1:numel(fields)
    s.(fields{i}) = b.(fields{i});
end
end

function s = state_layout(kernel_max_centers, s)
s.kernel_max_centers = kernel_max_centers;
s.idx_theta_rkhs = 16:(15+kernel_max_centers);
s.idx_S_eps = 16+kernel_max_centers;
s.idx_S_tran = 17+kernel_max_centers;
s.idx_kernel_l2 = 18+kernel_max_centers;
end

function restore_env(old_no_plots, old_overrides, old_keep_workspace)
setenv('PENDULUM_NO_PLOTS', old_no_plots);
setenv('PENDULUM_OVERRIDES', old_overrides);
setenv('PENDULUM_KEEP_WORKSPACE', old_keep_workspace);
end
