function cases = schedule_kernel_law_case_defs()
%SCHEDULE_KERNEL_LAW_CASE_DEFS Shared candidate definitions for schedule sweep.

windows = [
    0.030 0.008
    0.020 0.015
];

case_list = {};
for w = 1:size(windows, 1)
    hi = windows(w, 1);
    lo = windows(w, 2);

    case_list{end+1} = struct('name', sprintf('m1_grid_235_win_%g_%g', hi, lo), ...
        'params', struct('kernel_mode', 1, ...
                         'kernel_mode1_grid_sequence', [2 3 5], ...
                         'kernel_l2_high', hi, ...
                         'kernel_l2_low', lo));

    case_list{end+1} = struct('name', sprintf('m1_grid_246_win_%g_%g', hi, lo), ...
        'params', struct('kernel_mode', 1, ...
                         'kernel_mode1_grid_sequence', [2 4 6], ...
                         'kernel_mode1_max_grid_n', 6, ...
                         'kernel_l2_high', hi, ...
                         'kernel_l2_low', lo));

    case_list{end+1} = struct('name', sprintf('m3_endpoint_win_%g_%g', hi, lo), ...
        'params', struct('kernel_mode', 3, ...
                         'kernel_rep_point', 'endpoint', ...
                         'kernel_l2_high', hi, ...
                         'kernel_l2_low', lo));

    case_list{end+1} = struct('name', sprintf('m3_max_tracking_win_%g_%g', hi, lo), ...
        'params', struct('kernel_mode', 3, ...
                         'kernel_rep_point', 'max_tracking_error', ...
                         'kernel_l2_high', hi, ...
                         'kernel_l2_low', lo));
end

cases = [case_list{:}];
end
